#!/usr/bin/env node
/**
 * Turn the TNT logo into `graphics/templates/_assets.css`.
 *
 *   node graphics/scripts/build-assets.mjs
 *
 * Two things force this to be a build step rather than a plain `<img>`:
 *
 * 1. The logo has to take the ink of whatever direction it lands in — gold on
 *    the dark posts, deep green on the light one. So it ships as a greyscale
 *    *mask* and CSS supplies the colour. The source PNG is flat line art with
 *    an alpha channel, so the alpha channel alone is the whole mark.
 *
 * 2. Chromium treats every `file://` document as its own opaque origin and
 *    refuses to load a mask image across one. A template opened straight off
 *    disk — which is the whole design workflow — would silently mask itself to
 *    nothing. Inlining the mask as a `data:` URI sidesteps the origin entirely
 *    and leaves the templates dependency-free.
 *
 * Run it when the logo changes; the output is committed so nobody needs the
 * source artwork (or Python) to render a graphic.
 */

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { LOGO_SOURCE, MARKS as CROPS } from '../../scripts/logo-marks.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '../..');
const OUT = resolve(HERE, '../templates/_assets.css');

/**
 * The crops are shared with the website's own generator
 * (`scripts/build-logo.mjs`) so a post and the site header can't end up
 * cropping the mark differently; only the output size is decided here.
 */
const SOURCE = resolve(ROOT, LOGO_SOURCE);
const MARKS = [
  { name: 'crest', box: CROPS.crest, width: 512 },
  { name: 'lockup', box: CROPS.lockup, width: 560 },
];

/**
 * Pillow does the pixel work; it's already a dependency of
 * `scripts/optimize-photos.py`, and this script runs about as often as that
 * one does (i.e. when the owner changes an asset, not at render time).
 */
const PY = `
import base64, io, json, sys
from PIL import Image
src, marks = sys.argv[1], json.loads(sys.argv[2])
out = []
for m in marks:
    a = Image.open(src).crop(tuple(m["box"])).getchannel("A")
    a = a.crop(a.getbbox())                      # trim to the ink
    w = m["width"]; h = round(a.height * w / a.width)
    a = a.resize((w, h), Image.LANCZOS)
    # CSS mask-image reads the image's ALPHA channel by default, so the mark
    # has to live there — a plain greyscale PNG has no alpha, reads as fully
    # opaque, and masks to a solid rectangle. Luminance ("L") + the mark as
    # alpha ("A") keeps the file small and needs no 'mask-mode' override, so
    # the templates also render correctly in Safari and Firefox during design.
    la = Image.merge("LA", (Image.new("L", a.size, 255), a))
    buf = io.BytesIO()
    la.save(buf, "PNG", optimize=True)
    out.append({**m, "h": h, "w": w,
                "b64": base64.b64encode(buf.getvalue()).decode()})
print(json.dumps(out))
`;

const marks = JSON.parse(
  execFileSync('python3', ['-c', PY, SOURCE, JSON.stringify(MARKS)], {
    encoding: 'utf8',
    maxBuffer: 32 * 1024 * 1024,
  })
);

const rules = marks
  .map(
    // Unprefixed only — the sole renderer is Playwright's Chromium, which has
    // supported it for years, and a `-webkit-` duplicate doubles a file that is
    // already mostly base64.
    (m) => `.mark--${m.name} {
  aspect-ratio: ${m.w} / ${m.h};
  mask-image: url('data:image/png;base64,${m.b64}');
}`
  )
  .join('\n\n');

writeFileSync(
  OUT,
  `/* ==========================================================================
   GENERATED by graphics/scripts/build-assets.mjs — do not edit by hand.

   The TNT mark as a greyscale mask, inlined so it survives being opened from
   \`file://\` (Chromium blocks a mask image across an opaque origin) and so a
   template is one self-contained file. Colour comes from \`currentColor\` on the
   element — see \`.mark\` in _base.css.
   ========================================================================== */

${rules}
`,
  'utf8'
);

for (const m of marks) {
  console.log(`  ✓ .mark--${m.name}  ${m.w}×${m.h}  ${(m.b64.length / 1024).toFixed(0)} KB`);
}
console.log(`\n→ graphics/templates/_assets.css`);
