#!/usr/bin/env node
/**
 * Download the webfonts the templates use into `graphics/templates/fonts/` and
 * write the `@font-face` block that points at them.
 *
 * Rendering must be byte-identical on this laptop and in CI, which rules out
 * loading fonts over the network at screenshot time: Google Fonts serves a
 * different file to a different user agent, and a CI runner with no network
 * would silently fall back to a system face and reflow every graphic. So the
 * files are vendored and committed, and this script only ever runs when
 * somebody wants to add or update a family.
 *
 *   node graphics/scripts/fetch-fonts.mjs
 *
 * The generated `_fonts.css` is committed too — nothing at render time needs a
 * network.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const FONT_DIR = resolve(HERE, '../templates/fonts');

/**
 * The families in use, with the axis/weights each template actually sets. Ask
 * for the exact weights rather than a variable range: a static instance per
 * weight is a handful of KB and removes any question of Chromium synthesising
 * one differently between machines.
 */
const FAMILIES = [
  { family: 'Cinzel', weights: [400, 600, 700] },
  { family: 'Barlow Condensed', weights: [400, 500, 600, 700] },
  { family: 'Anton', weights: [400] },
  { family: 'Oswald', weights: [400, 500, 600, 700] },
  { family: 'Cormorant Garamond', weights: [400, 600, 700] },
];

/** Chrome asks for woff2; any other UA is served a fatter, older format. */
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const slug = (s) => s.toLowerCase().replace(/[^a-z0-9]+/g, '-');

async function fetchText(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} — ${url}`);
  return res.text();
}

/**
 * Pull one weight of one family. Google's CSS splits a family across unicode
 * subsets; we keep the `latin` block only — these graphics are English, and
 * the extra subsets triple the payload for glyphs no scoreline will ever use.
 */
async function grab(family, weight) {
  const url =
    `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family)}` +
    `:wght@${weight}&display=block`;
  const css = await fetchText(url);

  // Blocks are emitted subset-by-subset, each preceded by a `/* subset */`
  // comment. Take the one commented `latin`.
  const blocks = css.split('/*').map((b) => `/*${b}`);
  const latin = blocks.find((b) => b.startsWith('/* latin */'));
  if (!latin) throw new Error(`no latin subset for ${family} ${weight}`);

  const src = /url\((https:[^)]+\.woff2)\)/.exec(latin);
  if (!src) throw new Error(`no woff2 for ${family} ${weight}`);

  const file = `${slug(family)}-${weight}.woff2`;
  const bytes = Buffer.from(
    await (await fetch(src[1], { headers: { 'User-Agent': UA } })).arrayBuffer()
  );
  await writeFile(resolve(FONT_DIR, file), bytes);

  const range = /unicode-range:([^;]+);/.exec(latin);
  return { family, weight, file, bytes: bytes.length, range: range?.[1].trim() };
}

const faces = [];
await mkdir(FONT_DIR, { recursive: true });
for (const { family, weights } of FAMILIES) {
  for (const weight of weights) {
    const face = await grab(family, weight);
    faces.push(face);
    console.log(`  ✓ ${face.file}  ${(face.bytes / 1024).toFixed(1)} KB`);
  }
}

const css = `/* ==========================================================================
   GENERATED by graphics/scripts/fetch-fonts.mjs — do not edit by hand.

   Self-hosted so a render on a laptop and a render in CI produce the same
   pixels. \`font-display: block\` (not swap) matters here: a screenshot has no
   second chance to repaint, so the page must wait for the real face rather
   than flash a fallback into the PNG.
   ========================================================================== */

${faces
  .map(
    (f) => `@font-face {
  font-family: '${f.family}';
  font-style: normal;
  font-weight: ${f.weight};
  font-display: block;
  src: url('fonts/${f.file}') format('woff2');
}`
  )
  .join('\n\n')}
`;

await writeFile(resolve(HERE, '../templates/_fonts.css'), css);
console.log(
  `\n${faces.length} faces → graphics/templates/fonts/ ` +
    `(${(faces.reduce((n, f) => n + f.bytes, 0) / 1024).toFixed(0)} KB total)`
);
