// Vite/Astro ambient types (`import.meta.glob`, `import.meta.env`). Committed
// because `.astro/types.d.ts` is generated by `astro dev`/`sync` and gitignored,
// so a fresh CI checkout running `npm run typecheck` wouldn't otherwise see them.
/// <reference types="astro/client" />
